### ISSUE TITLE
Update to version 0.4.10 of micromodal

### ISSUE THREAD

**Issue by Holf** [robinmetral/svelte-micromodal#6]
I have been coming up against this issue: https://github.com/ghosh/Micromodal/issues/489#issuecomment-990167022

As stated in that comment, the issue does not happen with version `0.4.10` of `micromodal`. Perhaps `svelte-micromodal` could be updated to use this later version?

In the meantime, I have been able to force use of the later version by adding this to my `package.json` file:

```JSON
"overrides": {
    "micromodal": "0.4.10"
},
```

**Comment by robinmetral** [comment]
Hey @Holf, sure! Glad that you could test this on your end and can confirm that 0.4.10 works. Can you make a PR for this?

Otherwise I'll fix it, but since I'm on the road I'll need a few days (I can probably release a new version by the end of next week).

Thanks!

**Comment by robinmetral** [comment]
We just need to make sure that this doesn't happen with 0.4.10: https://github.com/ghosh/Micromodal/issues/490

This was the reason I pinned the version initially. To be honest I haven't really followed the issue thread, not sure whether it was fixed in the end

**Comment by Holf** [comment]
Hello! Thanks for the reply. I would gladly have done a PR but it looks to me as though that issue has not been fixed (excellent bug report, btw!).

There are some suggestions in that thread for fixes to `Micromodal` itself, and also some work-arounds in this and [another thread](https://github.com/ghosh/Micromodal/issues/505). I wouldn't want to push ahead and implement anything without getting your thoughts on it, first.

**Comment by robinmetral** [comment]
Thanks! :blush: 

I'm completely okay with any fix you think would make sense here. [This one](https://github.com/ghosh/Micromodal/issues/505#issuecomment-1610172087) for example would be a breaking change (changes to markup), but since this is in beta, I think we're good and I could release this in a `v0.0.9` with a `BREAKING CHANGE` mention.

Do you want to make a PR? I'd gladly review and accept it :slightly_smiling_face:

**Comment by Holf** [comment]
Cool, after a quick look through the ideas that layout-change suggestion was the one that jumped out to me, too. 😎  

I'll have a look at doing a PR, for sure.

**Comment by robinmetral** [comment]
The micromodal version was unpinned (and upgraded) in [svelte-micromodal@v0.0.9](https://www.npmjs.com/package/svelte-micromodal/v/0.0.9). Thank you @Holf!
